package openrtb

type ConnectionType int

const (
	CONNECTION_UNKNOWN ConnectionType = iota
	CONNECTION_ETHERNET
	CONNECTION_WIFI
	CONNECTION_CELLULAR_UNKNOWN
	CONNECTION_CELLULAR_2G
	CONNECTION_CELLULAR_3G
	CONNECTION_CELLULAR_4G
)
