package openrtb

type CreativeAttribute int

const (
	_ CreativeAttribute = iota
	CREATIVE_AUDIO_AUTO
	CREATIVE_AUDIO_USER
	CREATIVE_EXPANDABLE_AUTO
	CREATIVE_EXPANDABLE_USER_CLICK
	CREATIVE_EXPANDABLE_USER_ROLLOVER
	CREATIVE_IN_BANNER_VIDEO_AUTO
	CREATIVE_IN_BANNER_VIDEO_USER
	CREATIVE_POP
	CREATIVE_PROVOCATIVE
	CREATIVE_SMILEY
	CREATIVE_SURVEY
	CREATIVE_TEXT
	CREATIVE_INTERACTIVE
	CREATIVE_DIALOG
	CREATIVE_HAS_AUDIO_ON_OFF
	CREATIVE_SKIPPABLE
)
