// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package openrtb

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson31527abDecodeGithubComVungleVungoOpenrtb(in *jlexer.Lexer, out *Bid) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "impid":
			out.ImpressionID = string(in.String())
		case "price":
			out.Price = float64(in.Float64())
		case "nurl":
			out.WinNotificationURL = string(in.String())
		case "burl":
			out.BURL = string(in.String())
		case "lurl":
			out.LossNotificationURL = string(in.String())
		case "adm":
			out.AdMarkup = string(in.String())
		case "adid":
			out.AdID = string(in.String())
		case "adomain":
			if in.IsNull() {
				in.Skip()
				out.AdvertiserDomains = nil
			} else {
				in.Delim('[')
				if out.AdvertiserDomains == nil {
					if !in.IsDelim(']') {
						out.AdvertiserDomains = make([]string, 0, 4)
					} else {
						out.AdvertiserDomains = []string{}
					}
				} else {
					out.AdvertiserDomains = (out.AdvertiserDomains)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.AdvertiserDomains = append(out.AdvertiserDomains, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "bundle":
			out.Bundle = string(in.String())
		case "iurl":
			out.QualityImageURL = string(in.String())
		case "cid":
			out.CampaignID = string(in.String())
		case "crid":
			out.CreativeID = string(in.String())
		case "tactic":
			out.Tactic = string(in.String())
		case "cat":
			if in.IsNull() {
				in.Skip()
				out.Categories = nil
			} else {
				in.Delim('[')
				if out.Categories == nil {
					if !in.IsDelim(']') {
						out.Categories = make([]Category, 0, 4)
					} else {
						out.Categories = []Category{}
					}
				} else {
					out.Categories = (out.Categories)[:0]
				}
				for !in.IsDelim(']') {
					var v2 Category
					v2 = Category(in.String())
					out.Categories = append(out.Categories, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "attr":
			if in.IsNull() {
				in.Skip()
				out.CreativeAttributes = nil
			} else {
				in.Delim('[')
				if out.CreativeAttributes == nil {
					if !in.IsDelim(']') {
						out.CreativeAttributes = make([]CreativeAttribute, 0, 8)
					} else {
						out.CreativeAttributes = []CreativeAttribute{}
					}
				} else {
					out.CreativeAttributes = (out.CreativeAttributes)[:0]
				}
				for !in.IsDelim(']') {
					var v3 CreativeAttribute
					v3 = CreativeAttribute(in.Int())
					out.CreativeAttributes = append(out.CreativeAttributes, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "api":
			out.API = APIFramework(in.Int())
		case "protocol":
			out.Protocol = Protocol(in.Int())
		case "qagmediarating":
			out.QAGMediaRating = IQGMediaRating(in.Int())
		case "language":
			out.Language = string(in.String())
		case "dealid":
			out.DealID = string(in.String())
		case "w":
			out.Width = int(in.Int())
		case "h":
			out.Height = int(in.Int())
		case "wratio":
			out.WRatio = int(in.Int())
		case "hratio":
			out.HRatio = int(in.Int())
		case "exp":
			out.Exp = int(in.Int())
		case "ext":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Extension).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31527abEncodeGithubComVungleVungoOpenrtb(out *jwriter.Writer, in Bid) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"impid\":"
		out.RawString(prefix)
		out.String(string(in.ImpressionID))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	if in.WinNotificationURL != "" {
		const prefix string = ",\"nurl\":"
		out.RawString(prefix)
		out.String(string(in.WinNotificationURL))
	}
	if in.BURL != "" {
		const prefix string = ",\"burl\":"
		out.RawString(prefix)
		out.String(string(in.BURL))
	}
	if in.LossNotificationURL != "" {
		const prefix string = ",\"lurl\":"
		out.RawString(prefix)
		out.String(string(in.LossNotificationURL))
	}
	if in.AdMarkup != "" {
		const prefix string = ",\"adm\":"
		out.RawString(prefix)
		out.String(string(in.AdMarkup))
	}
	if in.AdID != "" {
		const prefix string = ",\"adid\":"
		out.RawString(prefix)
		out.String(string(in.AdID))
	}
	if len(in.AdvertiserDomains) != 0 {
		const prefix string = ",\"adomain\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v4, v5 := range in.AdvertiserDomains {
				if v4 > 0 {
					out.RawByte(',')
				}
				out.String(string(v5))
			}
			out.RawByte(']')
		}
	}
	if in.Bundle != "" {
		const prefix string = ",\"bundle\":"
		out.RawString(prefix)
		out.String(string(in.Bundle))
	}
	if in.QualityImageURL != "" {
		const prefix string = ",\"iurl\":"
		out.RawString(prefix)
		out.String(string(in.QualityImageURL))
	}
	if in.CampaignID != "" {
		const prefix string = ",\"cid\":"
		out.RawString(prefix)
		out.String(string(in.CampaignID))
	}
	if in.CreativeID != "" {
		const prefix string = ",\"crid\":"
		out.RawString(prefix)
		out.String(string(in.CreativeID))
	}
	if in.Tactic != "" {
		const prefix string = ",\"tactic\":"
		out.RawString(prefix)
		out.String(string(in.Tactic))
	}
	if len(in.Categories) != 0 {
		const prefix string = ",\"cat\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v6, v7 := range in.Categories {
				if v6 > 0 {
					out.RawByte(',')
				}
				out.String(string(v7))
			}
			out.RawByte(']')
		}
	}
	if len(in.CreativeAttributes) != 0 {
		const prefix string = ",\"attr\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.CreativeAttributes {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v9))
			}
			out.RawByte(']')
		}
	}
	if in.API != 0 {
		const prefix string = ",\"api\":"
		out.RawString(prefix)
		out.Int(int(in.API))
	}
	if in.Protocol != 0 {
		const prefix string = ",\"protocol\":"
		out.RawString(prefix)
		out.Int(int(in.Protocol))
	}
	if in.QAGMediaRating != 0 {
		const prefix string = ",\"qagmediarating\":"
		out.RawString(prefix)
		out.Int(int(in.QAGMediaRating))
	}
	if in.Language != "" {
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	if in.DealID != "" {
		const prefix string = ",\"dealid\":"
		out.RawString(prefix)
		out.String(string(in.DealID))
	}
	if in.Width != 0 {
		const prefix string = ",\"w\":"
		out.RawString(prefix)
		out.Int(int(in.Width))
	}
	if in.Height != 0 {
		const prefix string = ",\"h\":"
		out.RawString(prefix)
		out.Int(int(in.Height))
	}
	if in.WRatio != 0 {
		const prefix string = ",\"wratio\":"
		out.RawString(prefix)
		out.Int(int(in.WRatio))
	}
	if in.HRatio != 0 {
		const prefix string = ",\"hratio\":"
		out.RawString(prefix)
		out.Int(int(in.HRatio))
	}
	if in.Exp != 0 {
		const prefix string = ",\"exp\":"
		out.RawString(prefix)
		out.Int(int(in.Exp))
	}
	if len(in.Extension) != 0 {
		const prefix string = ",\"ext\":"
		out.RawString(prefix)
		out.Raw((in.Extension).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Bid) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31527abEncodeGithubComVungleVungoOpenrtb(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Bid) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31527abEncodeGithubComVungleVungoOpenrtb(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Bid) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31527abDecodeGithubComVungleVungoOpenrtb(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Bid) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31527abDecodeGithubComVungleVungoOpenrtb(l, v)
}
