// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package openrtb

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1db63384DecodeGithubComVungleVungoOpenrtb(in *jlexer.Lexer, out *Regulation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "coppa":
			if in.IsNull() {
				in.Skip()
				out.IsCoppaCompliant = nil
			} else {
				if out.IsCoppaCompliant == nil {
					out.IsCoppaCompliant = new(NumericBool)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.IsCoppaCompliant).UnmarshalJSON(data))
				}
			}
		case "ext":
			if m, ok := out.Extension.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Extension.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Extension = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1db63384EncodeGithubComVungleVungoOpenrtb(out *jwriter.Writer, in Regulation) {
	out.RawByte('{')
	first := true
	_ = first
	if in.IsCoppaCompliant != nil {
		const prefix string = ",\"coppa\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((*in.IsCoppaCompliant).MarshalJSON())
	}
	if in.Extension != nil {
		const prefix string = ",\"ext\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.Extension.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Extension.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Extension))
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Regulation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1db63384EncodeGithubComVungleVungoOpenrtb(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Regulation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1db63384DecodeGithubComVungleVungoOpenrtb(l, v)
}
